# Generated by Django 3.0.5 on 2020-05-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('motivo_consulta', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
            options={
                'db_table': 'cita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombres_empleado', models.CharField(max_length=50)),
                ('apellidos_empleado', models.CharField(max_length=50)),
                ('correo_electronico', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('tipo_usuario', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id_expediente', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('pulso', models.CharField(blank=True, max_length=7, null=True)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('presion_arterial', models.IntegerField(blank=True, null=True)),
                ('enfermedades', models.CharField(blank=True, max_length=50, null=True)),
                ('alergias', models.CharField(blank=True, max_length=50, null=True)),
                ('medicamentos', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_medico', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_medico', models.CharField(blank=True, max_length=15, null=True)),
                ('persona_refiere', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_consulta', models.CharField(blank=True, choices=[('Quirurgica', 'Quirurgica'), ('No Quirurgica', 'No Quirurgica')], max_length=50, null=True)),
                ('diagnostico', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'expediente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=100)),
                ('correo_electronico', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.IntegerField(primary_key=True, serialize=False)),
                ('medicamento', models.CharField(max_length=50)),
                ('observaciones', models.CharField(max_length=100)),
                ('id_paciente', models.IntegerField()),
                ('id_consulta', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'receta',
                'managed': False,
            },
        ),
    ]
