# Generated by Django 3.0.5 on 2020-05-17 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleados',
            options={'managed': False, 'permissions': (('is_surgeon', 'Is_Surgeon'), ('is_secretary', 'Is_Secretary'))},
        ),
    ]
